
USE task2;

DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS marks;
DROP TABLE IF EXISTS group;


CREATE TABLE course (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
	course_title VARCHAR(50) NOT NULL
) DEFAULT CHARSET=latin1;

CREATE TABLE student (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    id_group INTEGER UNSIGNED NOT NULL
) DEFAULT CHARSET=latin1;

CREATE TABLE teacher (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL
) DEFAULT CHARSET=latin1;

CREATE TABLE marks (
	id_course INTEGER UNSIGNED NOT NULL ,
    id_student INTEGER UNSIGNED NOT NULL ,
	mark INTEGER NOT NULL,
    PRIMARY KEY (id_course, id_student)
);

CREATE TABLE group (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
) DEFAULT CHARSET=latin1;
